=== Azure/review-checklists/checklists/checklist.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/Azure/review-checklists/checklist.schema.json",
    "title": "Review Checklist",
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "description": "The recommendations that make up the checklist.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "category": {
                        "type": "string",
                        "description": "The main category this recommendation applies to."
                    },
                    "subcategory": {
                        "type": "string",
                        "description": "The subcategory this recommendation applies to."
                    },
                    "waf": {
                        "type": "string",
                        "description": "The WAF (Well-Architected Framework) pillar this recommendation applies to."
                    },
                    "text": {
                        "type": "string",
                        "description": "A short summary of the recommendation."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description or additional information for the recommendation."
                    },
                    "guid": {
                        "type": "string",
                        "description": "A globally unique GUID for the recommendation."
                    },
                    "id": {
                        "type": "string",
                        "description": "A locally unique ID (only for this checklist) used primarily for sorting."
                    },
                    "link": {
                        "type": "string",
                        "description": "A link to documentation that provides more information or background."
                    },
                    "training": {
                        "type": "string",
                        "description": "A link to a training resource where you can learn more."
                    },
                    "graph": {
                        "type": "string",
                        "description": "An Azure Resource Graph query which checks if resources comply with the recommendation."
                    },
                    "graph_success": {
                        "type": "string",
                        "description": "[OBSOLETE: use 'graph' instead.] An Azure Resource Graph query which identifies resources that comply with the recommendation."
                    },
                    "graph_failure": {
                        "type": "string",
                        "description": "[OBSOLETE: use 'graph' instead.] An Azure Resource Graph query which identifies resources that do not comply with the recommendation."
                    },
                    "severity": {
                        "type": "string",
                        "description": "The severity of the recommendation."
                    },
                    "cost": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the cost of a solution."
                    },
                    "ha": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the high availability of a solution."
                    },
                    "scale": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the scale of a solution."
                    },
                    "security": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the security of a solution."
                    },
                    "simple": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the complexity of a solution."
                    },
                    "amm": {
                        "type": "boolean",
                        "description": "Whether a specific check is relevant for an AMM review."
                    },
                    "topics": {
                        "type":"array",
                        "description": "The topics that this recommendation applies to.",
                        "items": {
                            "type": "string",
                            "description": "The name of the topic."
                        }
                    }
                },
                "required": [
                    "category",
                    "subcategory",
                    "text",
                    "guid",
                    "severity"
                ]
            }
        },
        "categories": {
            "type": "array",
            "description": "The available categories for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the category."
                    }
                },
                "required": [ "name" ]
            }
        },
        "waf": {
            "type": "array",
            "description": "The available WAF (Well-Architected Framework) pillars for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the WAF (Well-Architected Framework) pillar."
                    }
                },
                "required": [ "name" ]
            }
        },
        "status": {
            "type": "array",
            "description": "The available statuses for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the status."
                    },
                    "description": {
                        "type": "string",
                        "description": "The description of the status."
                    }
                },
                "required": [ "name" ]
            }
        },
        "severities": {
            "type": "array",
            "description": "The available severities for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the severity."
                    }
                },
                "required": [ "name" ]
            }
        },
        "metadata": {
            "type": "object",
            "description": "The metadata for the checklist.",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the checklist."
                },
                "timestamp": {
                    "type": "string",
                    "description": "Date/time when the checklist was last modified."
                },
                "state": {
                    "type": "string",
                    "description": "State of the checklist (GA/Preview)."
                }
            },
            "required": [ "name" ]
        }
    }
}

=== Azure/review-checklists/checklists/azurespringapps_checklist.en.json
{
    "items": [
        {
            "category": "Application Deployment",
            "subcategory": "DevOps",
            "text": "Azure Spring Apps permits two deployments for every app, only one of which receives production traffic. You can achieve zero downtime with blue green deployment strategies. Blue green deployment is only available in Standard and Enterprise tiers. You could automate deployment using CI/CD with ADO/GitHub actions",
            "waf": "Reliability",
            "guid": "6d8e32a8-3892-479d-a40b-10f6b4f6f298",
            "cost": 1,
            "severity": "Medium",
            "link": "https://learn.microsoft.com/azure/spring-apps/concepts-blue-green-deployment-strategies"
        },
        {
            "category": "BC and DR",
            "subcategory": "Disaster Recovery",
            "text": "Azure Spring Apps instances could be created in multiple regions for your applications and traffic could be routed by Traffic Manager/Front Door.",
            "waf": "Reliability",
            "guid": "fbcb40ac-9480-4a6d-bcf4-8081252a6716",
            "cost": 1,
            "severity": "Medium",
            "link": "https://learn.microsoft.com/azure/architecture/web-apps/spring-apps/architectures/spring-apps-multi-region"
        },
        {
            "category": "BC and DR",
            "subcategory": "High Availability",
            "text": "In supported region, Azure Spring Apps can be deployed as zone redundant, which means that instances are automatically distributed across availability zones. This feature is only available in Standard and Enterprise tiers.",
            "waf": "Reliability",
            "guid": "ff1ae6a7-9301-4feb-9d11-56cd72f1d4ef",
            "cost": 1,
            "severity": "Medium",
            "link": "https://learn.microsoft.com/azure/reliability/reliability-spring-apps"
        },
        {
            "category": "BC and DR",
            "subcategory": "High Availability",
            "text": "Use more than 1 app instance for your apps",
            "waf": "Reliability",
            "guid": "ffc735ad-fbb1-4802-b43f-ad6387c4c066",
            "cost": 1,
            "severity": "Medium",
            "link": "https://learn.microsoft.com/azure/spring-apps/concept-understand-app-and-deployment"
        },
        {
            "category": "Operations",
            "subcategory": "Monitoring",
            "text": "Monitor Azure Spring Apps with logs, metrics and tracing. Integrate ASA with application insights and track failures and create workbooks.",
            "waf": "Reliability",
            "guid": "7504c230-6035-4183-95a5-85762acc6075",
            "cost": 1,
            "severity": "Medium",
            "link": "https://learn.microsoft.com/azure/spring-apps/diagnostic-services"
        },
        {
            "category": "Operations",
            "subcategory": "Scalability",
            "text": "Set up autoscaling in Spring Cloud Gateway",
            "waf": "Reliability",
            "guid": "1eb48d58-3eec-4ef5-80b0-d2b0dde3f0c6",
            "cost": 1,
            "severity": "Medium",
            "link": "https://learn.microsoft.com/azure/spring-apps/how-to-configure-enterprise-spring-cloud-gateway"
        },
        {
            "category": "Operations",
            "subcategory": "Scalability",
            "text": "Enable autoscale for the apps with Standard consumption & dedicated plan.",
            "waf": "Reliability",
            "guid": "97411607-b6fd-4335-99d1-9885faf4e392",
            "cost": 1,
            "severity": "Low",
            "link": "https://learn.microsoft.com/azure/spring-apps/how-to-setup-autoscale"
        },
        {
            "category": "Operations",
            "subcategory": "Support",
            "text": "Use Enterprise plan for commercial support of spring boot for mission critical apps. With other tiers you get OSS support.",
            "waf": "Reliability",
            "guid": "dfcaffd1-d27c-4ef2-998d-64c1df3a7ac3",
            "cost": 1,
            "severity": "Medium",
            "link": "https://learn.microsoft.com/azure/spring-apps/overview"
        }
    ],
    "categories": [
        {
            "name": "BC and DR"
        },
        {
            "name": "Operations"
        },
        {
            "name": "Application Deployment"
        }
    ],
    "waf": [
        {
            "name": "Reliability"
        },
        {
            "name": "Security"
        },
        {
            "name": "Cost"
        },
        {
            "name": "Operations"
        },
        {
            "name": "Performance"
        }
    ],
    "status": [
        {
            "name": "Not verified",
            "description": "This check has not been looked at yet"
        },
        {
            "name": "Open",
            "description": "There is an action item associated to this check"
        },
        {
            "name": "Fulfilled",
            "description": "This check has been verified, and there are no further action items associated to it"
        },
        {
            "name": "Not required",
            "description": "Recommendation understood, but not needed by current requirements"
        },
        {
            "name": "N/A",
            "description": "Not applicable for current design"
        }
    ],
    "severities": [
        {
            "name": "High"
        },
        {
            "name": "Medium"
        },
        {
            "name": "Low"
        }
    ],
    "metadata": {
        "name": "Azure Spring Apps Review",
        "state": "Preview",
        "timestamp": "November 15, 2023"
    }
}

=== Azure/review-checklists/checklists/asb_security_checklist.es.json
{
    "categories": [
        {
            "name": "Seguridad"
        }
    ],
    "items": [
        {
            "category": "Seguridad",
            "description": "Azure Service Bus Premium proporciona cifrado de datos en reposo. Si usa su propia clave, los datos aún se cifran con la clave administrada por Microsoft, pero además la clave administrada por Microsoft se cifrará con la clave administrada por el cliente. ",
            "guid": "87af4a79-1f89-439b-ba47-768e14c11567",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/configure-customer-managed-key",
            "severity": "Bajo",
            "subcategory": "Protección de datos",
            "text": "Usar la opción de clave administrada por el cliente en el cifrado de datos en reposo cuando sea necesario",
            "training": "https://docs.microsoft.com/learn/modules/plan-implement-administer-conditional-access/"
        },
        {
            "category": "Seguridad",
            "description": "La comunicación entre una aplicación cliente y un espacio de nombres de Azure Service Bus se cifra mediante Seguridad de la capa de transporte (TLS). Los espacios de nombres de Azure Service Bus permiten a los clientes enviar y recibir datos con TLS 1.0 y versiones posteriores. Para aplicar medidas de seguridad más estrictas, puede configurar el espacio de nombres de Service Bus para que requiera que los clientes envíen y reciban datos con una versión más reciente de TLS.",
            "guid": "5c1ea55b-46a9-448f-b8ae-7d7e4b475b6c",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/transport-layer-security-enforce-minimum-version",
            "severity": "Medio",
            "subcategory": "Protección de datos",
            "text": "Aplicar una versión mínima requerida de Seguridad de la capa de transporte (TLS) para las solicitudes ",
            "training": "https://docs.microsoft.com/learn/modules/secure-aad-users-with-mfa/"
        },
        {
            "category": "Seguridad",
            "description": "Al crear un espacio de nombres de Service Bus, se crea automáticamente una regla SAS denominada RootManageSharedAccessKey para el espacio de nombres. Esta directiva tiene permisos de administración para todo el espacio de nombres. Se recomienda tratar esta regla como una cuenta raíz administrativa y no usarla en la aplicación.  Se recomienda usar AAD como proveedor de autenticación con RBAC. ",
            "guid": "8bcbf59b-ce65-4de8-a03f-97879468d66a",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/service-bus-sas#shared-access-authorization-policies",
            "severity": "Medio",
            "subcategory": "Gestión de identidades y accesos",
            "text": "Evite usar una cuenta root cuando no sea necesario",
            "training": "https://docs.microsoft.com/learn/paths/azure-administrator-manage-identities-governance/"
        },
        {
            "category": "Seguridad",
            "description": "Una aplicación cliente de Service Bus que se ejecuta dentro de una aplicación del Servicio de aplicaciones de Azure o en una máquina virtual con entidades administradas habilitadas para la compatibilidad con recursos de Azure no necesita controlar reglas y claves de SAS, ni ningún otro token de acceso. La aplicación cliente solo necesita la dirección de extremo del espacio de nombres Mensajería de Service Bus. ",
            "guid": "786d60f9-6c96-4ad8-a55d-04c2b39c986b",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/service-bus-managed-service-identity",
            "severity": "Medio",
            "subcategory": "Gestión de identidades y accesos",
            "text": "Siempre que sea posible, la aplicación debe usar una identidad administrada para autenticarse en Azure Service Bus. Si no es así, considere la posibilidad de tener la credencial de almacenamiento (SAS, credencial de entidad de servicio) en Azure Key Vault o un servicio equivalente",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "Seguridad",
            "description": "Al crear permisos, proporcione un control detallado sobre el acceso de un cliente a Azure Service Bus. Los permisos de Azure Service Bus pueden y deben limitarse al nivel de recurso individual, por ejemplo, cola, tema o suscripción. ",
            "guid": "f615658d-e558-4f93-9249-b831112dbd7e",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/authenticate-application#azure-built-in-roles-for-azure-service-bus",
            "severity": "Alto",
            "subcategory": "Gestión de identidades y accesos",
            "text": "Usar RBAC del plano de datos con privilegios mínimos",
            "training": "https://docs.microsoft.com/learn/modules/explore-basic-services-identity-types/"
        },
        {
            "category": "Seguridad",
            "description": "Los registros de recursos de Azure Service Bus incluyen registros operativos, redes virtuales y registros de filtrado de IP. Los registros de auditoría en tiempo de ejecución capturan información de diagnóstico agregada para diversas operaciones de acceso al plano de datos (como enviar o recibir mensajes) en Service Bus.",
            "guid": "af12e7f9-43f6-4304-922d-929c2b1cd622",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/monitor-service-bus-reference",
            "severity": "Medio",
            "subcategory": "Monitorización",
            "text": "Habilite el registro para la investigación de seguridad. Usar Azure Monitor para realizar un seguimiento de los registros de recursos y los registros de auditoría en tiempo de ejecución (actualmente disponible solo en el nivel premium)",
            "training": "https://docs.microsoft.com/learn/paths/manage-identity-and-access/"
        },
        {
            "category": "Seguridad",
            "description": "De forma predeterminada, Azure Service Bus tiene una dirección IP pública y es accesible desde Internet. Los puntos de conexión privados permiten que el tráfico entre la red virtual y Azure Service Bus atraviese la red troncal de Microsoft. Además de eso, debe deshabilitar los puntos finales públicos si no se usan. ",
            "guid": "9ae669ca-48e4-4a85-b222-3ece8bb12307",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/private-link-service",
            "severity": "Medio",
            "subcategory": "Gestión de redes",
            "text": "Considere la posibilidad de usar puntos de conexión privados para acceder a Azure Service Bus y deshabilitar el acceso a la red pública cuando corresponda.",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "Seguridad",
            "description": "Con el firewall IP, puede restringir el punto final público a solo un conjunto de direcciones IPv4 o intervalos de direcciones IPv4 en notación CIDR (Classless Inter-Domain Routing). ",
            "guid": "ca5f06f1-58e3-4ea3-a92c-2de7e2165c3a",
            "link": "https://learn.microsoft.com/azure/service-bus-messaging/service-bus-ip-filtering",
            "severity": "Medio",
            "subcategory": "Gestión de redes",
            "text": "Considere la posibilidad de permitir solo el acceso al espacio de nombres de Azure Service Bus desde direcciones IP o intervalos específicos",
            "training": "https://docs.microsoft.com/learn/paths/implement-resource-mgmt-security/"
        }
    ],
    "metadata": {
        "name": "Azure Service Bus Review",
        "state": "Preview"
    },
    "severities": [
        {
            "name": "Alto"
        },
        {
            "name": "Medio"
        },
        {
            "name": "Bajo"
        }
    ],
    "status": [
        {
            "description": "Esta comprobación aún no se ha examinado",
            "name": "No verificado"
        },
        {
            "description": "Hay un elemento de acción asociado a esta comprobación",
            "name": "Abrir"
        },
        {
            "description": "Esta comprobación se ha comprobado y no hay más elementos de acción asociados a ella",
            "name": "Cumplido"
        },
        {
            "description": "Recomendación entendida, pero no necesaria por los requisitos actuales",
            "name": "No es necesario"
        },
        {
            "description": "No aplicable para el diseño actual",
            "name": "N/A"
        }
    ]
}
