=== Azure/review-checklists/checklists/checklist.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/Azure/review-checklists/checklist.schema.json",
    "title": "Review Checklist",
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "description": "The recommendations that make up the checklist.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "category": {
                        "type": "string",
                        "description": "The main category this recommendation applies to."
                    },
                    "subcategory": {
                        "type": "string",
                        "description": "The subcategory this recommendation applies to."
                    },
                    "waf": {
                        "type": "string",
                        "description": "The WAF (Well-Architected Framework) pillar this recommendation applies to."
                    },
                    "text": {
                        "type": "string",
                        "description": "A short summary of the recommendation."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description or additional information for the recommendation."
                    },
                    "guid": {
                        "type": "string",
                        "description": "A globally unique GUID for the recommendation."
                    },
                    "id": {
                        "type": "string",
                        "description": "A locally unique ID (only for this checklist) used primarily for sorting."
                    },
                    "link": {
                        "type": "string",
                        "description": "A link to documentation that provides more information or background."
                    },
                    "training": {
                        "type": "string",
                        "description": "A link to a training resource where you can learn more."
                    },
                    "graph": {
                        "type": "string",
                        "description": "An Azure Resource Graph query which checks if resources comply with the recommendation."
                    },
                    "graph_success": {
                        "type": "string",
                        "description": "[OBSOLETE: use 'graph' instead.] An Azure Resource Graph query which identifies resources that comply with the recommendation."
                    },
                    "graph_failure": {
                        "type": "string",
                        "description": "[OBSOLETE: use 'graph' instead.] An Azure Resource Graph query which identifies resources that do not comply with the recommendation."
                    },
                    "severity": {
                        "type": "string",
                        "description": "The severity of the recommendation."
                    },
                    "cost": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the cost of a solution."
                    },
                    "ha": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the high availability of a solution."
                    },
                    "scale": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the scale of a solution."
                    },
                    "security": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the security of a solution."
                    },
                    "simple": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the complexity of a solution."
                    },
                    "amm": {
                        "type": "boolean",
                        "description": "Whether a specific check is relevant for an AMM review."
                    },
                    "topics": {
                        "type":"array",
                        "description": "The topics that this recommendation applies to.",
                        "items": {
                            "type": "string",
                            "description": "The name of the topic."
                        }
                    }
                },
                "required": [
                    "category",
                    "subcategory",
                    "text",
                    "guid",
                    "severity"
                ]
            }
        },
        "categories": {
            "type": "array",
            "description": "The available categories for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the category."
                    }
                },
                "required": [ "name" ]
            }
        },
        "waf": {
            "type": "array",
            "description": "The available WAF (Well-Architected Framework) pillars for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the WAF (Well-Architected Framework) pillar."
                    }
                },
                "required": [ "name" ]
            }
        },
        "status": {
            "type": "array",
            "description": "The available statuses for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the status."
                    },
                    "description": {
                        "type": "string",
                        "description": "The description of the status."
                    }
                },
                "required": [ "name" ]
            }
        },
        "severities": {
            "type": "array",
            "description": "The available severities for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the severity."
                    }
                },
                "required": [ "name" ]
            }
        },
        "metadata": {
            "type": "object",
            "description": "The metadata for the checklist.",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the checklist."
                },
                "timestamp": {
                    "type": "string",
                    "description": "Date/time when the checklist was last modified."
                },
                "state": {
                    "type": "string",
                    "description": "State of the checklist (GA/Preview)."
                }
            },
            "required": [ "name" ]
        }
    }
}

=== Azure/review-checklists/checklists/eh_security_checklist.pt.json
{
    "categories": [
        {
            "name": "Segurança"
        }
    ],
    "items": [
        {
            "category": "Segurança",
            "description": "O Hub de Eventos do Azure fornece criptografia de dados em repouso. Se você usar sua própria chave, os dados ainda serão criptografados usando a chave gerenciada pela Microsoft, mas, além disso, a chave gerenciada pela Microsoft será criptografada usando a chave gerenciada pelo cliente. ",
            "guid": "7aaf12e7-b94e-4f6e-847d-2d92981b1cd6",
            "link": "https://learn.microsoft.com/azure/event-hubs/configure-customer-managed-key",
            "severity": "Baixo",
            "subcategory": "Proteção de Dados",
            "text": "Usar a opção de chave gerenciada pelo cliente na criptografia de dados em repouso quando necessário",
            "training": "https://docs.microsoft.com/learn/modules/plan-implement-administer-conditional-access/"
        },
        {
            "category": "Segurança",
            "description": "Os namespaces dos Hubs de Eventos do Azure permitem que os clientes enviem e recebam dados com o TLS 1.0 e superior. Para impor medidas de segurança mais rigorosas, você pode configurar o namespace dos Hubs de Eventos para exigir que os clientes enviem e recebam dados com uma versão mais recente do TLS. Se um namespace de Hubs de Eventos exigir uma versão mínima do TLS, todas as solicitações feitas com uma versão mais antiga falharão. ",
            "guid": "d2f54b29-769e-43a6-a0e7-828ac936657e",
            "link": "https://learn.microsoft.com/azure/event-hubs/transport-layer-security-configure-minimum-version",
            "severity": "Média",
            "subcategory": "Proteção de Dados",
            "text": "Impor uma versão mínima necessária do Transport Layer Security (TLS) para solicitações ",
            "training": "https://docs.microsoft.com/learn/modules/secure-aad-users-with-mfa/"
        },
        {
            "category": "Segurança",
            "description": "Quando você cria um namespace de Hubs de Eventos, uma regra de política chamada RootManageSharedAccessKey é criada automaticamente para o namespace. Essa política tem permissões de gerenciamento para todo o namespace. É recomendável que você trate essa regra como uma conta raiz administrativa e não a use em seu aplicativo. Recomenda-se o uso do AAD como um provedor de autenticação com RBAC. ",
            "guid": "13b0f566-4b1e-4944-a459-837ee79d6c6d",
            "link": "https://learn.microsoft.com/azure/event-hubs/authorize-access-shared-access-signature#shared-access-authorization-policies",
            "severity": "Média",
            "subcategory": "Gerenciamento de Identidade e Acesso",
            "text": "Evite usar a conta root quando não for necessário",
            "training": "https://docs.microsoft.com/learn/paths/azure-administrator-manage-identities-governance/"
        },
        {
            "category": "Segurança",
            "description": "As identidades gerenciadas para recursos do Azure podem autorizar o acesso aos recursos dos Hubs de Eventos usando credenciais do Azure AD de aplicativos em execução em VMs (Máquinas Virtuais) do Azure, aplicativos de Função, Conjuntos de Escala de Máquina Virtual e outros serviços. Usando identidades gerenciadas para recursos do Azure junto com a autenticação do Azure AD, você pode evitar o armazenamento de credenciais com seus aplicativos executados na nuvem. ",
            "guid": "3a365a5c-7acb-4e48-abd5-4cd79f2e8776",
            "link": "https://learn.microsoft.com/azure/event-hubs/authenticate-managed-identity?tabs=latest",
            "severity": "Média",
            "subcategory": "Gerenciamento de Identidade e Acesso",
            "text": "Quando possível, seu aplicativo deve estar usando uma identidade gerenciada para autenticar no Hub de Eventos do Azure. Caso contrário, considere ter a credencial de armazenamento (SAS, credencial da entidade de serviço) no Cofre da Chave do Azure ou em um serviço equivalente",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "Segurança",
            "description": "Ao criar permissões, forneça controle refinado sobre o acesso de um cliente ao Hub de Eventos do Azure. As permissões no Hub de Eventos do Azure podem e devem ter como escopo o nível de recurso individual, por exemplo, grupo de consumidores, entidade do hub de eventos, namespaces do hub de eventos, etc.",
            "guid": "8357c559-675c-45ee-a5b8-6ad8844ce3b2",
            "link": "https://learn.microsoft.com/azure/event-hubs/authorize-access-azure-active-directory#azure-built-in-roles-for-azure-event-hubs",
            "severity": "Alto",
            "subcategory": "Gerenciamento de Identidade e Acesso",
            "text": "Usar RBAC do plano de dados de privilégios mínimos",
            "training": "https://docs.microsoft.com/learn/modules/explore-basic-services-identity-types/"
        },
        {
            "category": "Segurança",
            "description": "Os logs de recursos do Hub de Eventos do Azure incluem logs operacionais, rede virtual e logs do Kafka. Os logs de auditoria de tempo de execução capturam informações de diagnóstico agregadas para todas as operações de acesso ao plano de dados (como eventos de envio ou recebimento) em Hubs de Eventos.",
            "guid": "b38b875b-a1cf-4104-a900-3a4d3ce474db",
            "link": "https://learn.microsoft.com/azure/event-hubs/monitor-event-hubs-reference",
            "severity": "Média",
            "subcategory": "Monitorização",
            "text": "Habilite o log para investigação de segurança. Usar o Azure Monitor para capturar métricas e logs, como logs de recursos, logs de auditoria de tempo de execução e logs do Kafka",
            "training": "https://docs.microsoft.com/learn/paths/manage-identity-and-access/"
        },
        {
            "category": "Segurança",
            "description": "O Hub de Eventos do Azure, por padrão, tem um endereço IP público e pode ser acessado pela Internet. Os pontos de extremidade privados permitem que o tráfego entre sua rede virtual e o Hub de Eventos do Azure percorra a rede de backbone da Microsoft. Além disso, você deve desabilitar pontos de extremidade públicos se eles não forem usados. ",
            "guid": "5abca2a4-eda1-4dae-8cc9-5d48c6b791dc",
            "link": "https://learn.microsoft.com/azure/event-hubs/private-link-service",
            "severity": "Média",
            "subcategory": "Rede",
            "text": "Considere o uso de pontos de extremidade privados para acessar o Hub de Eventos do Azure e desabilitar o acesso à rede pública, quando aplicável.",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "Segurança",
            "description": "Com o firewall IP, você pode restringir ainda mais o ponto de extremidade público a apenas um conjunto de endereços IPv4 ou intervalos de endereços IPv4 na notação CIDR (Roteamento entre Domínios Sem Classe). ",
            "guid": "a0e6c465-89e5-458b-a37d-3974d1112dbd",
            "link": "https://learn.microsoft.com/azure/event-hubs/event-hubs-ip-filtering",
            "severity": "Média",
            "subcategory": "Rede",
            "text": "Considere permitir apenas o acesso ao namespace do Hub de Eventos do Azure a partir de endereços IP ou intervalos específicos",
            "training": "https://docs.microsoft.com/learn/paths/implement-resource-mgmt-security/"
        }
    ],
    "metadata": {
        "name": "Azure Event Hub Review",
        "state": "Preview"
    },
    "severities": [
        {
            "name": "Alto"
        },
        {
            "name": "Média"
        },
        {
            "name": "Baixo"
        }
    ],
    "status": [
        {
            "description": "Esta verificação ainda não foi analisada",
            "name": "Não verificado"
        },
        {
            "description": "Há um item de ação associado a essa verificação",
            "name": "Abrir"
        },
        {
            "description": "Essa verificação foi verificada e não há mais itens de ação associados a ela",
            "name": "Cumprido"
        },
        {
            "description": "Recomendação entendida, mas não necessária pelos requisitos atuais",
            "name": "Não é necessário"
        },
        {
            "description": "Não aplicável ao projeto atual",
            "name": "N/A"
        }
    ]
}

=== Azure/review-checklists/checklists/eh_security_checklist.ja.json
{
    "categories": [
        {
            "name": "安全"
        }
    ],
    "items": [
        {
            "category": "安全",
            "description": "Azure イベント ハブでは、保存データの暗号化が提供されます。独自のキーを使用する場合、データは引き続き Microsoft マネージド キーを使用して暗号化されますが、さらに Microsoft マネージド キーはカスタマー マネージド キーを使用して暗号化されます。",
            "guid": "7aaf12e7-b94e-4f6e-847d-2d92981b1cd6",
            "link": "https://learn.microsoft.com/azure/event-hubs/configure-customer-managed-key",
            "severity": "低い",
            "subcategory": "データ保護",
            "text": "必要に応じて、保存データの暗号化でカスタマー マネージド キー オプションを使用する",
            "training": "https://docs.microsoft.com/learn/modules/plan-implement-administer-conditional-access/"
        },
        {
            "category": "安全",
            "description": "Azure Event Hubs 名前空間を使用すると、クライアントは TLS 1.0 以降を使用してデータを送受信できます。より厳格なセキュリティ対策を適用するには、クライアントが新しいバージョンの TLS を使用してデータを送受信することを要求するように Event Hubs 名前空間を構成できます。Event Hubs 名前空間で最小バージョンの TLS が必要な場合、古いバージョンで行われた要求はすべて失敗します。",
            "guid": "d2f54b29-769e-43a6-a0e7-828ac936657e",
            "link": "https://learn.microsoft.com/azure/event-hubs/transport-layer-security-configure-minimum-version",
            "severity": "中程度",
            "subcategory": "データ保護",
            "text": "要求に最低限必要なバージョンのトランスポート層セキュリティ (TLS) を適用する",
            "training": "https://docs.microsoft.com/learn/modules/secure-aad-users-with-mfa/"
        },
        {
            "category": "安全",
            "description": "Event Hubs 名前空間を作成すると、その名前空間に対して RootManageSharedAccessKey という名前のポリシー規則が自動的に作成されます。このポリシーには、名前空間全体に対する管理アクセス許可があります。このルールは管理ルートアカウントのように扱い、アプリケーションでは使用しないことをお勧めします。RBAC で認証プロバイダーとして AAD を使用することをお勧めします。",
            "guid": "13b0f566-4b1e-4944-a459-837ee79d6c6d",
            "link": "https://learn.microsoft.com/azure/event-hubs/authorize-access-shared-access-signature#shared-access-authorization-policies",
            "severity": "中程度",
            "subcategory": "ID およびアクセス管理",
            "text": "不要な場合はrootアカウントを使用しないでください",
            "training": "https://docs.microsoft.com/learn/paths/azure-administrator-manage-identities-governance/"
        },
        {
            "category": "安全",
            "description": "Azure リソースのマネージド ID では、Azure 仮想マシン (VM)、関数アプリ、仮想マシン スケール セット、およびその他のサービスで実行されているアプリケーションから Azure AD 資格情報を使用して、Event Hubs リソースへのアクセスを承認できます。Azure リソースのマネージド ID を Azure AD 認証と共に使用することで、クラウドで実行されるアプリケーションに資格情報を格納する必要がなくなります。",
            "guid": "3a365a5c-7acb-4e48-abd5-4cd79f2e8776",
            "link": "https://learn.microsoft.com/azure/event-hubs/authenticate-managed-identity?tabs=latest",
            "severity": "中程度",
            "subcategory": "ID およびアクセス管理",
            "text": "可能であれば、アプリケーションはマネージド ID を使用して Azure Event Hub に対する認証を行う必要があります。そうでない場合は、ストレージ資格情報 (SAS、サービス プリンシパル資格情報) を Azure Key Vault または同等のサービスに配置することを検討してください。",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "安全",
            "description": "アクセス許可を作成するときに、Azure Event Hub へのクライアントのアクセスをきめ細かく制御できるようにします。Azure Event Hub のアクセス許可は、コンシューマー グループ、イベント ハブ エンティティ、イベント ハブ名前空間など、個々のリソース レベルにスコープを設定することができ、またそうする必要があります。",
            "guid": "8357c559-675c-45ee-a5b8-6ad8844ce3b2",
            "link": "https://learn.microsoft.com/azure/event-hubs/authorize-access-azure-active-directory#azure-built-in-roles-for-azure-event-hubs",
            "severity": "高い",
            "subcategory": "ID およびアクセス管理",
            "text": "最小特権データ プレーン RBAC を使用する",
            "training": "https://docs.microsoft.com/learn/modules/explore-basic-services-identity-types/"
        },
        {
            "category": "安全",
            "description": "Azure イベント ハブ リソース ログには、操作ログ、仮想ネットワーク、Kafka ログが含まれます。ランタイム監査ログは、Event Hubs 内のすべてのデータ プレーン アクセス操作 (送信イベントや受信イベントなど) の集計された診断情報をキャプチャします。",
            "guid": "b38b875b-a1cf-4104-a900-3a4d3ce474db",
            "link": "https://learn.microsoft.com/azure/event-hubs/monitor-event-hubs-reference",
            "severity": "中程度",
            "subcategory": "モニタリング",
            "text": "セキュリティ調査のログ記録を有効にします。Azure Monitor を使用して、リソース ログ、ランタイム監査ログ、Kafka ログなどのメトリックとログをキャプチャする",
            "training": "https://docs.microsoft.com/learn/paths/manage-identity-and-access/"
        },
        {
            "category": "安全",
            "description": "Azure イベント ハブには既定でパブリック IP アドレスがあり、インターネットでアクセスできます。プライベート エンドポイントを使用すると、仮想ネットワークと Azure イベント ハブ間のトラフィックが Microsoft バックボーン ネットワーク経由で通過できます。それに加えて、パブリックエンドポイントが使用されていない場合は無効にする必要があります。",
            "guid": "5abca2a4-eda1-4dae-8cc9-5d48c6b791dc",
            "link": "https://learn.microsoft.com/azure/event-hubs/private-link-service",
            "severity": "中程度",
            "subcategory": "ネットワーキング",
            "text": "プライベート エンドポイントを使用して Azure Event Hub にアクセスし、該当する場合はパブリック ネットワーク アクセスを無効にすることを検討してください。",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "安全",
            "description": "IP ファイアウォールを使用すると、パブリック エンドポイントを IPv4 アドレスのセットまたは CIDR (クラスレス ドメイン間ルーティング) 表記の IPv4 アドレス範囲のみに制限できます。",
            "guid": "a0e6c465-89e5-458b-a37d-3974d1112dbd",
            "link": "https://learn.microsoft.com/azure/event-hubs/event-hubs-ip-filtering",
            "severity": "中程度",
            "subcategory": "ネットワーキング",
            "text": "特定の IP アドレスまたは範囲からの Azure イベント ハブ名前空間へのアクセスのみを許可することを検討してください",
            "training": "https://docs.microsoft.com/learn/paths/implement-resource-mgmt-security/"
        }
    ],
    "metadata": {
        "name": "Azure Event Hub Review",
        "state": "Preview"
    },
    "severities": [
        {
            "name": "高い"
        },
        {
            "name": "中程度"
        },
        {
            "name": "低い"
        }
    ],
    "status": [
        {
            "description": "このチェックはまだ確認されていません",
            "name": "未確認"
        },
        {
            "description": "このチェックに関連付けられているアクションアイテムがあります",
            "name": "開ける"
        },
        {
            "description": "このチェックは検証済みであり、それ以上のアクションアイテムは関連付けられていません",
            "name": "達成"
        },
        {
            "description": "推奨事項は理解されていますが、現在の要件では必要ありません",
            "name": "必須ではありません"
        },
        {
            "description": "現在のデザインには適用できません",
            "name": "該当なし"
        }
    ]
}

=== Azure/review-checklists/checklists/azurespringapps_checklist.pt.json
{
    "categories": [
        {
            "name": "BC e DR"
        },
        {
            "name": "Operações"
        },
        {
            "name": "Implantação de aplicativos"
        }
    ],
    "items": [
        {
            "category": "Implantação de aplicativos",
            "cost": 1,
            "guid": "6d8e32a8-3892-479d-a40b-10f6b4f6f298",
            "link": "https://learn.microsoft.com/azure/spring-apps/concepts-blue-green-deployment-strategies",
            "severity": "Média",
            "subcategory": "DevOps",
            "text": "Os Aplicativos Spring do Azure permitem duas implantações para cada aplicativo, apenas um dos quais recebe tráfego de produção. Você pode obter tempo de inatividade zero com estratégias de implantação em verde azul. A implantação verde azul só está disponível nas camadas Standard e Enterprise. Você pode automatizar a implantação usando CI/CD com ações do ADO/GitHub",
            "waf": "Fiabilidade"
        },
        {
            "category": "BC e DR",
            "cost": 1,
            "guid": "fbcb40ac-9480-4a6d-bcf4-8081252a6716",
            "link": "https://learn.microsoft.com/azure/architecture/web-apps/spring-apps/architectures/spring-apps-multi-region",
            "severity": "Média",
            "subcategory": "Recuperação de desastres",
            "text": "As instâncias do Azure Spring Apps podem ser criadas em várias regiões para seus aplicativos e o tráfego pode ser roteado pelo Gerenciador de Tráfego/Front Door.",
            "waf": "Fiabilidade"
        },
        {
            "category": "BC e DR",
            "cost": 1,
            "guid": "ff1ae6a7-9301-4feb-9d11-56cd72f1d4ef",
            "link": "https://learn.microsoft.com/azure/reliability/reliability-spring-apps",
            "severity": "Média",
            "subcategory": "Alta Disponibilidade",
            "text": "Na região com suporte, os Aplicativos Spring do Azure podem ser implantados como zona redundante, o que significa que as instâncias são distribuídas automaticamente entre zonas de disponibilidade. Esse recurso só está disponível nas camadas Standard e Enterprise.",
            "waf": "Fiabilidade"
        },
        {
            "category": "BC e DR",
            "cost": 1,
            "guid": "ffc735ad-fbb1-4802-b43f-ad6387c4c066",
            "link": "https://learn.microsoft.com/azure/spring-apps/concept-understand-app-and-deployment",
            "severity": "Média",
            "subcategory": "Alta Disponibilidade",
            "text": "Usar mais de 1 instância de aplicativo para seus aplicativos",
            "waf": "Fiabilidade"
        },
        {
            "category": "Operações",
            "cost": 1,
            "guid": "7504c230-6035-4183-95a5-85762acc6075",
            "link": "https://learn.microsoft.com/azure/spring-apps/diagnostic-services",
            "severity": "Média",
            "subcategory": "Monitorização",
            "text": "Monitore os Aplicativos Spring do Azure com logs, métricas e rastreamento. Integre o ASA com insights de aplicativos e rastreie falhas e crie pastas de trabalho.",
            "waf": "Fiabilidade"
        },
        {
            "category": "Operações",
            "cost": 1,
            "guid": "1eb48d58-3eec-4ef5-80b0-d2b0dde3f0c6",
            "link": "https://learn.microsoft.com/azure/spring-apps/how-to-configure-enterprise-spring-cloud-gateway",
            "severity": "Média",
            "subcategory": "Escalabilidade",
            "text": "Configurar o dimensionamento automático no Spring Cloud Gateway",
            "waf": "Fiabilidade"
        },
        {
            "category": "Operações",
            "cost": 1,
            "guid": "97411607-b6fd-4335-99d1-9885faf4e392",
            "link": "https://learn.microsoft.com/azure/spring-apps/how-to-setup-autoscale",
            "severity": "Baixo",
            "subcategory": "Escalabilidade",
            "text": "Habilite o dimensionamento automático para os aplicativos com o plano de consumo padrão e dedicado.",
            "waf": "Fiabilidade"
        },
        {
            "category": "Operações",
            "cost": 1,
            "guid": "dfcaffd1-d27c-4ef2-998d-64c1df3a7ac3",
            "link": "https://learn.microsoft.com/azure/spring-apps/overview",
            "severity": "Média",
            "subcategory": "Apoio",
            "text": "Use o plano Enterprise para suporte comercial de inicialização spring para aplicativos de missão crítica. Com outras camadas, você obtém suporte a OSS.",
            "waf": "Fiabilidade"
        }
    ],
    "metadata": {
        "name": "Azure Spring Apps Review",
        "state": "Preview",
        "timestamp": "November 15, 2023"
    },
    "severities": [
        {
            "name": "Alto"
        },
        {
            "name": "Média"
        },
        {
            "name": "Baixo"
        }
    ],
    "status": [
        {
            "description": "Esta verificação ainda não foi analisada",
            "name": "Não verificado"
        },
        {
            "description": "Há um item de ação associado a essa verificação",
            "name": "Abrir"
        },
        {
            "description": "Essa verificação foi verificada e não há outros itens de ação associados a ela",
            "name": "Cumprido"
        },
        {
            "description": "Recomendação compreendida, mas não necessária pelos requisitos atuais",
            "name": "Não é necessário"
        },
        {
            "description": "Não aplicável ao projeto atual",
            "name": "N/A"
        }
    ],
    "waf": [
        {
            "name": "Fiabilidade"
        },
        {
            "name": "Segurança"
        },
        {
            "name": "Custar"
        },
        {
            "name": "Operações"
        },
        {
            "name": "Desempenho"
        }
    ]
}
