=== Azure/review-checklists/checklists/checklist.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/Azure/review-checklists/checklist.schema.json",
    "title": "Review Checklist",
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "description": "The recommendations that make up the checklist.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "category": {
                        "type": "string",
                        "description": "The main category this recommendation applies to."
                    },
                    "subcategory": {
                        "type": "string",
                        "description": "The subcategory this recommendation applies to."
                    },
                    "waf": {
                        "type": "string",
                        "description": "The WAF (Well-Architected Framework) pillar this recommendation applies to."
                    },
                    "text": {
                        "type": "string",
                        "description": "A short summary of the recommendation."
                    },
                    "description": {
                        "type": "string",
                        "description": "A long description or additional information for the recommendation."
                    },
                    "guid": {
                        "type": "string",
                        "description": "A globally unique GUID for the recommendation."
                    },
                    "id": {
                        "type": "string",
                        "description": "A locally unique ID (only for this checklist) used primarily for sorting."
                    },
                    "link": {
                        "type": "string",
                        "description": "A link to documentation that provides more information or background."
                    },
                    "training": {
                        "type": "string",
                        "description": "A link to a training resource where you can learn more."
                    },
                    "graph": {
                        "type": "string",
                        "description": "An Azure Resource Graph query which checks if resources comply with the recommendation."
                    },
                    "graph_success": {
                        "type": "string",
                        "description": "[OBSOLETE: use 'graph' instead.] An Azure Resource Graph query which identifies resources that comply with the recommendation."
                    },
                    "graph_failure": {
                        "type": "string",
                        "description": "[OBSOLETE: use 'graph' instead.] An Azure Resource Graph query which identifies resources that do not comply with the recommendation."
                    },
                    "severity": {
                        "type": "string",
                        "description": "The severity of the recommendation."
                    },
                    "cost": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the cost of a solution."
                    },
                    "ha": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the high availability of a solution."
                    },
                    "scale": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the scale of a solution."
                    },
                    "security": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the security of a solution."
                    },
                    "simple": {
                        "type": "integer",
                        "description": "[EXPERIMENTAL] Documents the impact of this recommendation to the complexity of a solution."
                    },
                    "amm": {
                        "type": "boolean",
                        "description": "Whether a specific check is relevant for an AMM review."
                    },
                    "topics": {
                        "type":"array",
                        "description": "The topics that this recommendation applies to.",
                        "items": {
                            "type": "string",
                            "description": "The name of the topic."
                        }
                    }
                },
                "required": [
                    "category",
                    "subcategory",
                    "text",
                    "guid",
                    "severity"
                ]
            }
        },
        "categories": {
            "type": "array",
            "description": "The available categories for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the category."
                    }
                },
                "required": [ "name" ]
            }
        },
        "waf": {
            "type": "array",
            "description": "The available WAF (Well-Architected Framework) pillars for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the WAF (Well-Architected Framework) pillar."
                    }
                },
                "required": [ "name" ]
            }
        },
        "status": {
            "type": "array",
            "description": "The available statuses for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the status."
                    },
                    "description": {
                        "type": "string",
                        "description": "The description of the status."
                    }
                },
                "required": [ "name" ]
            }
        },
        "severities": {
            "type": "array",
            "description": "The available severities for the checklist items.",
            "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the severity."
                    }
                },
                "required": [ "name" ]
            }
        },
        "metadata": {
            "type": "object",
            "description": "The metadata for the checklist.",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the checklist."
                },
                "timestamp": {
                    "type": "string",
                    "description": "Date/time when the checklist was last modified."
                },
                "state": {
                    "type": "string",
                    "description": "State of the checklist (GA/Preview)."
                }
            },
            "required": [ "name" ]
        }
    }
}

=== Azure/review-checklists/checklists/eh_security_checklist.es.json
{
    "categories": [
        {
            "name": "Seguridad"
        }
    ],
    "items": [
        {
            "category": "Seguridad",
            "description": "Azure Event Hub proporciona cifrado de datos en reposo. Si usa su propia clave, los datos aún se cifran con la clave administrada por Microsoft, pero además la clave administrada por Microsoft se cifrará con la clave administrada por el cliente. ",
            "guid": "7aaf12e7-b94e-4f6e-847d-2d92981b1cd6",
            "link": "https://learn.microsoft.com/azure/event-hubs/configure-customer-managed-key",
            "severity": "Bajo",
            "subcategory": "Protección de datos",
            "text": "Usar la opción de clave administrada por el cliente en el cifrado de datos en reposo cuando sea necesario",
            "training": "https://docs.microsoft.com/learn/modules/plan-implement-administer-conditional-access/"
        },
        {
            "category": "Seguridad",
            "description": "Los espacios de nombres de Azure Event Hubs permiten a los clientes enviar y recibir datos con TLS 1.0 y versiones posteriores. Para aplicar medidas de seguridad más estrictas, puede configurar el espacio de nombres de Centros de eventos para que requiera que los clientes envíen y reciban datos con una versión más reciente de TLS. Si un espacio de nombres de Centros de eventos requiere una versión mínima de TLS, se producirá un error en las solicitudes realizadas con una versión anterior. ",
            "guid": "d2f54b29-769e-43a6-a0e7-828ac936657e",
            "link": "https://learn.microsoft.com/azure/event-hubs/transport-layer-security-configure-minimum-version",
            "severity": "Medio",
            "subcategory": "Protección de datos",
            "text": "Aplicar una versión mínima requerida de Seguridad de la capa de transporte (TLS) para las solicitudes ",
            "training": "https://docs.microsoft.com/learn/modules/secure-aad-users-with-mfa/"
        },
        {
            "category": "Seguridad",
            "description": "Al crear un espacio de nombres de Centros de eventos, se crea automáticamente una regla de directiva denominada RootManageSharedAccessKey para el espacio de nombres. Esta directiva tiene permisos de administración para todo el espacio de nombres. Se recomienda tratar esta regla como una cuenta raíz administrativa y no usarla en la aplicación. Se recomienda usar AAD como proveedor de autenticación con RBAC. ",
            "guid": "13b0f566-4b1e-4944-a459-837ee79d6c6d",
            "link": "https://learn.microsoft.com/azure/event-hubs/authorize-access-shared-access-signature#shared-access-authorization-policies",
            "severity": "Medio",
            "subcategory": "Gestión de identidades y accesos",
            "text": "Evite usar una cuenta root cuando no sea necesario",
            "training": "https://docs.microsoft.com/learn/paths/azure-administrator-manage-identities-governance/"
        },
        {
            "category": "Seguridad",
            "description": "Las identidades administradas para los recursos de Azure pueden autorizar el acceso a los recursos de Centros de eventos mediante credenciales de Azure AD desde aplicaciones que se ejecutan en máquinas virtuales (VM), aplicaciones de función, conjuntos de escalado de máquinas virtuales y otros servicios. Mediante el uso de identidades administradas para recursos de Azure junto con la autenticación de Azure AD, puede evitar almacenar credenciales con las aplicaciones que se ejecutan en la nube. ",
            "guid": "3a365a5c-7acb-4e48-abd5-4cd79f2e8776",
            "link": "https://learn.microsoft.com/azure/event-hubs/authenticate-managed-identity?tabs=latest",
            "severity": "Medio",
            "subcategory": "Gestión de identidades y accesos",
            "text": "Siempre que sea posible, la aplicación debe usar una identidad administrada para autenticarse en Azure Event Hub. Si no es así, considere la posibilidad de tener la credencial de almacenamiento (SAS, credencial de entidad de servicio) en Azure Key Vault o un servicio equivalente",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "Seguridad",
            "description": "Al crear permisos, proporcione un control detallado sobre el acceso de un cliente a Azure Event Hub. Los permisos en Azure Event Hub pueden y deben limitarse al nivel de recurso individual, por ejemplo, grupo de consumidores, entidad de centro de eventos, espacios de nombres de centros de eventos, etc.",
            "guid": "8357c559-675c-45ee-a5b8-6ad8844ce3b2",
            "link": "https://learn.microsoft.com/azure/event-hubs/authorize-access-azure-active-directory#azure-built-in-roles-for-azure-event-hubs",
            "severity": "Alto",
            "subcategory": "Gestión de identidades y accesos",
            "text": "Usar RBAC del plano de datos con privilegios mínimos",
            "training": "https://docs.microsoft.com/learn/modules/explore-basic-services-identity-types/"
        },
        {
            "category": "Seguridad",
            "description": "Los registros de recursos de Azure Event Hub incluyen registros operativos, registros de red virtual y registros de Kafka. Los registros de auditoría en tiempo de ejecución capturan información de diagnóstico agregada para todas las operaciones de acceso al plano de datos (como eventos de envío o recepción) en Centros de eventos.",
            "guid": "b38b875b-a1cf-4104-a900-3a4d3ce474db",
            "link": "https://learn.microsoft.com/azure/event-hubs/monitor-event-hubs-reference",
            "severity": "Medio",
            "subcategory": "Monitorización",
            "text": "Habilite el registro para la investigación de seguridad. Use Azure Monitor para capturar métricas y registros, como registros de recursos, registros de auditoría en tiempo de ejecución y registros de Kafka",
            "training": "https://docs.microsoft.com/learn/paths/manage-identity-and-access/"
        },
        {
            "category": "Seguridad",
            "description": "De forma predeterminada, Azure Event Hub tiene una dirección IP pública y es accesible desde Internet. Los puntos de conexión privados permiten que el tráfico entre la red virtual y Azure Event Hub atraviese la red troncal de Microsoft. Además de eso, debe deshabilitar los puntos finales públicos si no se usan. ",
            "guid": "5abca2a4-eda1-4dae-8cc9-5d48c6b791dc",
            "link": "https://learn.microsoft.com/azure/event-hubs/private-link-service",
            "severity": "Medio",
            "subcategory": "Gestión de redes",
            "text": "Considere la posibilidad de usar puntos de conexión privados para acceder a Azure Event Hub y deshabilitar el acceso a la red pública cuando corresponda.",
            "training": "https://docs.microsoft.com/learn/modules/azure-ad-privileged-identity-management/"
        },
        {
            "category": "Seguridad",
            "description": "Con el firewall IP, puede restringir el punto final público a solo un conjunto de direcciones IPv4 o rangos de direcciones IPv4 en notación CIDR (enrutamiento entre dominios sin clases). ",
            "guid": "a0e6c465-89e5-458b-a37d-3974d1112dbd",
            "link": "https://learn.microsoft.com/azure/event-hubs/event-hubs-ip-filtering",
            "severity": "Medio",
            "subcategory": "Gestión de redes",
            "text": "Considere la posibilidad de permitir solo el acceso al espacio de nombres de Azure Event Hub desde direcciones IP o intervalos específicos",
            "training": "https://docs.microsoft.com/learn/paths/implement-resource-mgmt-security/"
        }
    ],
    "metadata": {
        "name": "Azure Event Hub Review",
        "state": "Preview"
    },
    "severities": [
        {
            "name": "Alto"
        },
        {
            "name": "Medio"
        },
        {
            "name": "Bajo"
        }
    ],
    "status": [
        {
            "description": "Esta comprobación aún no se ha examinado",
            "name": "No verificado"
        },
        {
            "description": "Hay un elemento de acción asociado a esta comprobación",
            "name": "Abrir"
        },
        {
            "description": "Esta comprobación se ha comprobado y no hay más elementos de acción asociados a ella",
            "name": "Cumplido"
        },
        {
            "description": "Recomendación entendida, pero no necesaria por los requisitos actuales",
            "name": "No es necesario"
        },
        {
            "description": "No aplicable para el diseño actual",
            "name": "N/A"
        }
    ]
}

=== Azure/review-checklists/checklists/acr_security_checklist.ja.json
{
    "categories": [
        {
            "name": "安全"
        }
    ],
    "items": [
        {
            "category": "安全",
            "description": "データの流出を防ぐために画像のエクスポートを無効にします。これにより、別の ACR インスタンスへのイメージのインポートが防止されることに注意してください。",
            "guid": "ab91932c-9fc9-4d1b-a880-37f5e6bfcb9e",
            "link": "https://learn.microsoft.com/azure/container-registry/data-loss-prevention",
            "severity": "高い",
            "subcategory": "データ保護",
            "text": "Azure コンテナー レジストリ イメージのエクスポートを無効にする"
        },
        {
            "category": "安全",
            "description": "Azure コンテナー レジストリの Azure Policy を有効にすることで、監査コンプライアンスの可視性を有効にする",
            "guid": "d503547c-d447-4e82-9128-a7100f1cac6d",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-azure-policy",
            "severity": "高い",
            "subcategory": "データ保護",
            "text": "Azure コンテナー レジストリの Azure ポリシーを有効にする"
        },
        {
            "category": "安全",
            "description": "Azure Key Vault (AKV) は、コンテナー イメージやその他の成果物に署名して検証するために、AKV プラグイン (azure-kv) という表記法で使用できる署名キーを格納するために使用されます。Azure コンテナー レジストリ (ACR) を使用すると、az または oras CLI コマンドを使用してこれらの署名をアタッチできます。",
            "guid": "d345293c-7639-4637-a551-c5c04e401955",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-tutorial-sign-build-push",
            "severity": "高い",
            "subcategory": "データ保護",
            "text": "表記法を使用したコンテナーの署名と検証 (公証人 v2)"
        },
        {
            "category": "安全",
            "description": "Azure コンテナー レジストリでは、格納するイメージやその他の成果物が自動的に暗号化されます。既定では、Azure はサービス マネージド キーを使用して保存時のレジストリ コンテンツを自動的に暗号化します。カスタマー マネージド キーを使用すると、既定の暗号化を追加の暗号化レイヤーで補完できます。",
            "guid": "0bd05dc2-efd5-4d76-8d41-d2500cc47b49",
            "link": "https://learn.microsoft.com/azure/container-registry/tutorial-customer-managed-keys",
            "severity": "中程度",
            "subcategory": "データ保護",
            "text": "カスタマー マネージド キーを使用したレジストリの暗号化"
        },
        {
            "category": "安全",
            "description": "マネージド ID を使用して、クライアント アプリケーションからの ACRPull/プッシュ RBAC アクセスをセキュリティで保護する",
            "guid": "8f42d78e-79dc-47b3-9bd2-a1a27e7a8e90",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-authentication-managed-identity",
            "severity": "高い",
            "subcategory": "ID とアクセス制御",
            "text": "サービス プリンシパルの代わりにマネージド ID を使用して接続する"
        },
        {
            "category": "安全",
            "description": "ローカル管理者アカウントは既定で無効になっているため、有効にしないでください。代わりにトークンまたは RBAC ベースのアクセス方法を使用する",
            "guid": "be0e38ce-e297-411b-b363-caaab79b198d",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-authentication-managed-identity",
            "severity": "高い",
            "subcategory": "ID とアクセス制御",
            "text": "管理プレーンアクセスのローカル認証を無効にする"
        },
        {
            "category": "安全",
            "description": "管理者アカウントを無効にし、ACR プル/プッシュ操作のプリンシパルに RBAC ロールを割り当てる",
            "guid": "387e5ced-126c-4d13-8af5-b20c6998a646",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-roles?tabs=azure-cli",
            "severity": "高い",
            "subcategory": "ID とアクセス制御",
            "text": "ID プリンシパルに管理アクセス権を付与するのではなく、AcrPull & AcrPush RBAC ロールを割り当てる"
        },
        {
            "category": "安全",
            "description": "匿名プル/プッシュアクセスを無効にする",
            "guid": "e338997e-41c7-47d7-acf6-a62a1194956d",
            "link": "https://learn.microsoft.com/azure/container-registry/anonymous-pull-access#configure-anonymous-pull-access",
            "severity": "中程度",
            "subcategory": "ID とアクセス制御",
            "text": "匿名プルアクセスを無効にする"
        },
        {
            "category": "安全",
            "description": "トークン認証では、AAD プリンシパルへの割り当てはサポートされていません。提供されたトークンは、トークンにアクセスできるすべてのユーザーが使用できます",
            "guid": "698dc3a2-fd27-4b2e-8870-1a1252beedf6",
            "link": "https://learn.microsoft.com/en-gb/azure/container-registry/container-registry-authentication?tabs=azure-cli",
            "severity": "高い",
            "subcategory": "ID とアクセス制御",
            "text": "リポジトリスコープのアクセストークンを無効にする"
        },
        {
            "category": "安全",
            "description": "信頼されたネットワーク内のプライベート エンドポイントの背後にある ACR にコンテナー イメージをデプロイする",
            "guid": "b3bec3d4-f343-47c1-936d-b55f27a71eee",
            "severity": "高い",
            "subcategory": "ID とアクセス制御",
            "text": "信頼できる環境からイメージを展開する"
        },
        {
            "category": "安全",
            "description": "ACR 対象ユーザーを持つトークンのみを認証に使用できます。ACR の条件付きアクセス ポリシーを有効にするときに使用",
            "guid": "3a041fd3-2947-498b-8288-b3c6a56ceb54",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-enable-conditional-access-policy",
            "severity": "中程度",
            "subcategory": "ID とアクセス制御",
            "text": "認証のために Azure ARM 対象ユーザー トークンを無効にする"
        },
        {
            "category": "安全",
            "description": "ログ記録と監視の中心的な宛先として Log Analytics に \"リポジトリ イベント\" と \"ログイン イベント\" を送信するように診断設定を設定します。これにより、ACR リソース自体のコントロール プレーン アクティビティを監視できます。",
            "guid": "8a488cde-c486-42bc-9bd2-1be77f26e5e6",
            "link": "https://learn.microsoft.com/azure/container-registry/monitor-service",
            "severity": "中程度",
            "subcategory": "ログ記録と監視",
            "text": "診断ログを有効にする"
        },
        {
            "category": "安全",
            "description": "サービスでは、サービス レベルの IP ACL フィルター規則 (NSG または Azure Firewall ではない) を使用するか、[パブリック ネットワーク アクセスを無効にする] トグル スイッチを使用して、パブリック ネットワーク アクセスを無効にすることができます。",
            "guid": "21d41d25-00b7-407a-b9ea-b40fd3290798",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-private-link",
            "severity": "中程度",
            "subcategory": "ネットワークセキュリティ",
            "text": "プライベート リンクを使用した受信ネットワーク アクセスの制御"
        },
        {
            "category": "安全",
            "description": "受信ネットワーク アクセスが Private Link を使用してセキュリティで保護されている場合は、パブリック ネットワーク アクセスを無効にする",
            "guid": "cd289ced-6b17-4db8-8554-62f2aee4553a",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-access-selected-networks#disable-public-network-access",
            "severity": "中程度",
            "subcategory": "ネットワークセキュリティ",
            "text": "パブリックネットワークアクセスを無効にする"
        },
        {
            "category": "安全",
            "description": "ACR プレミアム SKU のみがプライベート リンク アクセスをサポートします",
            "guid": "fc833934-8b26-42d6-ac5f-512925498f6d",
            "link": "https://learn.microsoft.com/azure/container-registry/container-registry-skus",
            "severity": "中程度",
            "subcategory": "ネットワークセキュリティ",
            "text": "プライベート リンク (Premium SKU) をサポートする Azure コンテナー レジストリ SKU を使用する"
        },
        {
            "category": "安全",
            "description": "コンテナー用 Azure Defender または同等のサービスを使用して、コンテナー イメージの脆弱性をスキャンする必要があります",
            "guid": "bad37dac-43bc-46ce-8d7a-a9b24604489a",
            "link": "https://learn.microsoft.com/azure/defender-for-cloud/defender-for-containers-introduction",
            "severity": "低い",
            "subcategory": "ネットワークセキュリティ",
            "text": "コンテナーの Defender が Azure コンテナー レジストリの脆弱性をスキャンできるようにする"
        },
        {
            "category": "安全",
            "description": "DevSecOps プラクティスに従って脆弱性が検証およびスキャンされた信頼できるコードをデプロイします。",
            "guid": "4451e1a2-d345-4293-a763-9637a551c5c0",
            "severity": "中程度",
            "subcategory": "脆弱性管理",
            "text": "検証済みのコンテナー イメージをデプロイする"
        },
        {
            "category": "安全",
            "description": "サポートされているプラットフォーム、プログラミング言語、プロトコル、およびフレームワークの最新バージョンを使用します。",
            "guid": "4e401955-387e-45ce-b126-cd132af5b20c",
            "severity": "高い",
            "subcategory": "脆弱性管理",
            "text": "最新のプラットフォーム、言語、プロトコル、フレームワークを使用する"
        }
    ],
    "metadata": {
        "name": "Azure Container Registry Security Review",
        "state": "Preview"
    },
    "severities": [
        {
            "name": "高い"
        },
        {
            "name": "中程度"
        },
        {
            "name": "低い"
        }
    ],
    "status": [
        {
            "description": "このチェックはまだ確認されていません",
            "name": "未確認"
        },
        {
            "description": "このチェックに関連付けられているアクションアイテムがあります",
            "name": "開ける"
        },
        {
            "description": "このチェックは検証済みであり、それ以上のアクションアイテムは関連付けられていません",
            "name": "達成"
        },
        {
            "description": "現在のデザインには適用できません",
            "name": "該当なし"
        },
        {
            "description": "必須ではありません",
            "name": "必須ではありません"
        }
    ]
}
